### ISSUE TITLE
any way for devices to be able to write to microSD card directly?

### ISSUE THREAD

**Issue by runz0rd** [AlbrechtL/BTT_ESPWebDAV#7]
My use case: i have a device that will write to a sd card daily. I want to be able to remotely pull that data to another device.
Problem: the BTT-SD-TF-Cloud is read-only

Any way i can get around this?

**Comment by tomik76** [comment]
I also have device that need to write to sd card. I know that FYSTEC SD_WIFI can do this. Maybe yo can upload its firmware to BTT and check if it works [https://github.com/FYSETC/ESPWebDAV](https://github.com/FYSETC/ESPWebDAV)
It looks very similar, but it does not fit to my device SD card slot (microswitch blocks it, you need sd card extender). Check this out [http://www.apneaboard.com/forums/Thread-split-FYSETC-SD-Wifi-Possible-FlashAir-Replacement](http://www.apneaboard.com/forums/Thread-split-FYSETC-SD-Wifi-Possible-FlashAir-Replacement)
also page 10 there mentions trouble with BTT (_The SDIO portion is only setup to be used as an SPI interface_ _Note: all SD card interfaces that communicate via SDIO mode cannot
be used;_ ) Is it the reason we cannot write to SD CARD? Or we  just need to modify notch in PCB to make it writable.
Is it possible to modifiy BTT SD Cloud to alow to write to sd card?

**Comment by runz0rd** [comment]
Unfortunately my use case also requires an SDIO interface, which BTT does not support at all :disappointed:
